using System;

namespace Ela.Compilation
{
	internal static class OpHelper
	{
		internal static int[] OpSize = 
		{
			1, //Nop
			1, //Len
			1, //Pushunit
			1, //Pushptr
			1, //Pushelem
			1, //PushI4_0
			1, //PushI1_0
			1, //PushI1_1
			1, //Pop
			1, //Popelem
			1, //Pushseq
			1, //Pushstr_0
			1, //Listadd
			1, //Listgen
			1, //Listtail
			1, //Listelem
			1, //Ret
			1, //ConvI1
			1, //ConvI4
			1, //ConvR4
			1, //ConvStr
			1, //ConvCh
			1, //ConvI8
			1, //ConvR8
			1, //ConvSeq
			1, //Add
			1, //Mul
			1, //Div
			1, //Rem
			1, //Pow
			1, //Sub
			1, //Shr
			1, //Shl
			1, //Ctag
			1, //Htag
			1, //Ceq
			1, //Cneq
			1, //Clt
			1, //Cgt
			1, //Cgteq
			1, //Clteq
			1, //AndBw
			1, //OrBw
			1, //Xor
			1, //Not
			1, //Neg
			1, //Pos
			1, //NotBw
			1, //Dup
			1, //Calla
			1, //Valueof
			1, //Newseq
			1, //Newlist
			1, //Newlazy
			1, //Newmod
			1, //Newarr_0
			1, //Newtup_2
			1, //Cout
			1, //Throw
			1, //Typeof
			1, //Term
			1, //NewI8
			1, //NewR8
			1, //Leave
			1, //Calld
			5, //Callt
			5, //Start
			5, //Call
			5, //Incr
			5, //Decr
			5, //Cop
			5, //Pushstr
			5, //PushCh
			5, //PushI4
			5, //PushR4
			5, //Pusharg
			5, //Pushperv
			5, //Pushvar
			5, //Pushfld
			5, //Popvar
			5, //Popfld
			5, //Runmod
			5, //Hasfld
			5, //Br
			5, //Brtrue
			5, //Brfalse
			5, //Brptr
			5, //Br_lt
			5, //Br_gt
			5, //Br_eq
			5, //Br_neq
			5, //Brdyn
			5, //Yield
			5, //Newfun
			5, //Newfund
			5, //Newfuns
			5, //Newrec
			5, //Newarr
			5, //Newtup
			5, //Settag
			5, //Epilog
		};
	}
}